image:
  repository: public.ecr.aws/aws-secrets-manager/secrets-store-csi-driver-provider-aws
  pullPolicy: IfNotPresent
  # Defaults to appVersion
  tag:

nameOverride: ""
fullnameOverride: ""
providerVolume: "/etc/kubernetes/secrets-store-csi-providers"

podLabels: {}
podAnnotations: {}

resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    cpu: 50m
    memory: 100Mi

nodeSelector: {}

tolerations: []

port: 8989

updateStrategy:
  type: RollingUpdate

rbac:
  install: true

securityContext:
  privileged: false
  allowPrivilegeEscalation: false
